### PR TITLE
feat: add Bedrock support

### PR DESCRIPTION
**Pull request by smartcontracts**

### CODE REVIEW

**Comment by dandavid3000** [comment]
Hi !
I have the issue below from bedrock-init_1. It seems something is wrong with the connection to download bedrock file
```

bedrock-init_1    | curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
simple-optimism-node_bedrock-init_1 exited with code 56

bedrock-init_1    | Downloading bedrock.tar...
healthcheck_1     | {"level":30,"time":1686366721760,"msg":"starting app server"}
healthcheck_1     | {"level":30,"time":1686366721773,"port":7300,"hostname":"0.0.0.0","msg":"app server started"}
healthcheck_1     | {"level":30,"time":1686366721773,"msg":"starting main loop"}
healthcheck_1     | {"level":50,"time":1686366721788,"msg":"target client not connected"}
fault-detector_1  | {"level":30,"time":1686366722574,"msg":"starting app server"}
fault-detector_1  | {"level":30,"time":1686366722593,"port":7300,"hostname":"0.0.0.0","msg":"app server started"}
fault-detector_1  | {"level":30,"time":1686366722593,"msg":"initializing service"}
fault-detector_1  | {"level":30,"time":1686366722593,"msg":"waiting for L1 provider..."}
fault-detector_1  | {"level":30,"time":1686366723470,"msg":"L1 provider connected"}
fault-detector_1  | {"level":30,"time":1686366723470,"msg":"waiting for L2 provider..."}
fault-detector_1  | {"level":30,"time":1686366723473,"msg":"L2 provider not connected, retrying..."}
bedrock-init_1    | curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
simple-optimism-node_bedrock-init_1 exited with code 33

```

**Comment by smartcontracts** [comment]
Hmmm weird sounds like Cloudflare R2 isn't handling the byte range request that would be needed to resume the download. Gonna see if that's something I can fix on the Cloudflare side or if I need some other mechanism to resume downloads.

**Comment by dandavid3000** [comment]
> Hmmm weird sounds like Cloudflare R2 isn't handling the byte range request that would be needed to resume the download. Gonna see if that's something I can fix on the Cloudflare side or if I need some other mechanism to resume downloads.
> 
> Edit: I ran the curl command locally and resuming the download seems to work fine. Gonna dig in more... Edit: I wasn't able to reproduce this. Can you try changing `set -eou` to `set -exu` at the top of `init-bedrock.sh` to get more detailed output about what's being executed?

Is this the file [mainnet_bedrock.rar](https://oplabs.notion.site/Bedrock-Mission-Control-EXTERNAL-fca344b1f799447cb1bcf3aae62157c5) that we're gonna download ? 

It's good if we can have an option to in .env to extract a local file. That could save time.

I'll test the command above and come back later

**Comment by dandavid3000** [comment]
After downloading the file for 285gb. bedrock init is dead. We need a mechanism to resume the download process
```

bedrock-init_1    | ++ ls -l /downloads/bedrock.tar
' Wed, $'Accept-Encoding\r' $'max-age=14400\r' $'MISS\r' '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=IxMvEzP2GRNh3Kr7WD73y066J2PhYV2YU62HiPNOIiRQzlmG7ni%2BjL9inaBSKcuzJKr3wRy%2FYgrD7Y809J' $'cloudflare\r' $'7d53ec398b49f138-CDG\r' 'h3=":443";' '{printf "Download Progress: %.2f%%\n", $5/size*100}'
bedrock-init_1    | awk: line 2: syntax error at or near end of file
bedrock-init_1    | 
bedrock-init_1    | + echo ''
bedrock-init_1    | + true
bedrock-init_1    | + sleep 60
bedrock-init_1    | ++ ls -l /downloads/bedrock.tar
' Wed, $'Accept-Encoding\r' $'max-age=14400\r' $'MISS\r' '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=IxMvEzP2GRNh3Kr7WD73y066J2PhYV2YU62HiPNOIiRQzlmG7ni%2BjL9inaBSKcuzJKr3wRy%2FYgrD7Y809J' $'cloudflare\r' $'7d53ec398b49f138-CDG\r' 'h3=":443";' '{printf "Download Progress: %.2f%%\n", $5/size*100}'
bedrock-init_1    | awk: line 2: syntax error at or near end of file
bedrock-init_1    | + echo ''
bedrock-init_1    | + true
bedrock-init_1    | + sleep 60
bedrock-init_1    | 
bedrock-init_1    | curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by taempark** [comment]
@smartcontracts using wget instead of curl will do. We experienced the same problem for r2, too 😭

**Comment by dandavid3000** [comment]
> @smartcontracts using wget instead of curl will do. We experienced the same problem for r2, too 😭

You can download the file with the link above and then use symbolic link to link it into the docker file.

ln -s path_to_source/mainnet_bedrock.rar path_to_docker/simple-optimism-node_torrent_downloads/_data/bedrock.tar

Simply disable the download part from bash script from file simple-optimism-node/scripts/init-bedrock.sh

```
echo "Fetching download link..."
#BEDROCK_TAR_DOWNLOAD=$(config "bedrock/$NETWORK_NAME/bedrock-download")
#echo $BEDROCK_TAR_DOWNLOAD
```

Re-run the docker and it should work :D
However the speed is slow. You might need to add --snapshot=false for start-op-geth.sh to speed up the process.

**Comment by smartcontracts** [comment]
Hi hi, getting back to this. I just fixed the issue with the broken l2geth init script. Need to investigate the curl issue further.

**Comment by smartcontracts** [comment]
curl with `-C -` is supposed to resume the download if possible, I wonder why it's breaking

**Comment by smartcontracts** [comment]
Going to push an update that uses wget instead of curl

**Comment by smartcontracts** [comment]
Ok pushed an update to use wget instead of curl

**Comment by kchojn** [comment]
Gm, this branch works with Bedrock? Or still needs some fixes/features

**Comment by kchojn** [comment]
> Gm, this branch works with Bedrock? Or still needs some fixes/features

I confirm, it works with `Bedrock`

**Pull request merged**
